[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Bahadır Araz", email = "bahadiraraz@protonmail.com"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

